name: AD Users

on:
  push:
    branches:
      - dev
    paths:
      - "AD/**"

env:
  AADGroupName: "WVDUsers"
  DAGName: "Host-Pool-01-DAG"
  rgName: "RG-WVD-00"        


jobs:
  Permission-Utilisateurs:
    runs-on: windows-2019

    steps:

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Droits Utilisateurs
      uses: azure/powershell@v1
      with:
        inlineScript: |
          New-AzRoleAssignment -ObjectId (Get-AzADGroup -DisplayName ${{ env.AADGroupName }}).Id -RoleDefinitionName "Desktop Virtualization User" -ResourceName ${{ env.dagName }} -ResourceGroupName ${{ env.rgName }} -ResourceType 'Microsoft.DesktopVirtualization/applicationGroups'
        azPSVersion: '4.7.0'         