name: Module AD

on:
  push:
    branches:
      - dev
    paths:
      - "AD/**"


jobs:
  Permission-Utilisateurs:
    runs-on: windows-2019

    steps:

      - name: Installation modules AzureAD
        shell: pwsh
        run: |
          Install-Module -Name AzureAD -force
          Import-Module AzureAD

        
