name: Deploiement infra Windows Virtual Desktop

on:
  push:
    branches:
      - dev


jobs:
  Build-Packer-Image:
    runs-on: ubuntu-latest

    steps:

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Image Packer
        run: | 
          packer validate -var 'sp_Id=1c5a056d-9d4b-4074-9ea9-bdf7bb95b201' -var 'sp_Secret={{ secrets.SP_SECRET }}' -var 'tenant_Id=7a4c45f9-0a5a-433f-aed3-30f9328b8a4d' -var 'subscription_Id=45d70f51-2e63-4daa-8870-27e468ba9baa'  ./Packer/Wvd-Image.json          