name: Deploiement infra Windows Virtual Desktop

on:
  push:
    branches:
      - dev


jobs:
  Build-Packer-Image:
    runs-on: ubuntu-latest

    steps:

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Image Packer
        run: | 
          packer validate -var 'image_Name=test' \ ./Packer/Wvd-Image.json
          