name: Deploiement infra Windows Virtual Desktop

on:
  push:
    branches:
      - dev


jobs:
  Build-Packer-Image:
    runs-on: ubuntu-latest

    steps:

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Image Packer
        run: | 
          packer validate -var 'sp_Id=1c5a056d-9d4b-4074-9ea9-bdf7bb95b201' -var 'sp_Secret={{ secrets.SP_SECRET }}' -var 'tenant_Id={{ secrets.TENANT_ID }}' -var 'subscription_Id={{ secrets.SUBCRIPTION_ID }}'  ./Packer/Wvd-Image.json
          