name: Deploiement infra Windows Virtual Desktop

on:
  push:
    branches:
      - dev

env:
  IMAGE_RGNAME: "RG-Image-Packer"
  IMAGE_NAME: "WVD-FSlogix-VLC-Image-v0.007-test"
  IMAGE_LOCATION: "East US 2"

jobs:
  Build-Packer-Image:
    runs-on: ubuntu-20.04

    steps:

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
          
      - name: List RG
        run: |
          az group show --name RG-Image-Packer