name: Deploiement infra Windows Virtual Desktop

on:
  push:
    branches:
      - dev


jobs:
  Build-Packer-Image:
    runs-on: ubuntu-20.04

    steps:

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Image Packer
        run:
          packer build ./Packer/Wvd-Image.json -var 'sp_Id=1c5a056d-9d4b-4074-9ea9-bdf7bb95b201'
          