name: Deploiement d'une infra Windows Virtual Desktop

on:
  push:
    branches:
      - dev
    paths:
      - "Packer/**"

env:
# Varialbles Image Packer
  IMAGE_RGNAME: "RG-Images-WVD"
  IMAGE_NAME: "WVD-FSlogix-VLC-Image-v0.0007-test"
  IMAGE_LOCATION: "eastus2"
  OS: "Windows"
  PUBLISHER: "MicrosoftWindowsDesktop"
  OFFER: "office-365"
  SKU: "20h2-evd-o365pp"
  SHAREIMAGEGALLERY: "sharedImageGallery"
  IMAGE_DEFINITION: "windows_WVD"
  PUB_GALLERY: "AzureWVD"
  SHARE_PROFILS_LOCATION: "storagefslogix.file.core.windows.net"
  SHARE_PROFILS_FOLDER: "profiles"

jobs:
  Build-Packer-Image:
    runs-on: ubuntu-20.04

    steps:

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation Shared image gallery
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
            az group create --name ${{ env.IMAGE_RGNAME }} --location ${{ env.IMAGE_LOCATION }}

      - name: Creation du ressource groupe
        run: | 
          packer validate -var 'sp_Id=${{ secrets.SP_ID }}' -var 'sp_Secret=${{ secrets.SP_SECRET }}' -var 'tenant_Id=${{ secrets.TENANT_ID }}' -var 'subscription_Id=${{ secrets.SUBSCRIPTION_ID }}' -var 'image_Rgname=${{ env.IMAGE_RGNAME }}' -var 'image_Name=${{ env.IMAGE_NAME }}' -var 'image_location=${{ env.IMAGE_LOCATION }}' -var 'Os=${{ env.OS }}' -var 'Publisher=${{ env.PUBLISHER}}' -var 'Offer=${{ env.OFFER }}' -var 'Sku=${{ env.SKU }}' -var 'Share_Profils_location=${{ env.SHARE_PROFILS_LOCATION }}' -var 'Share_Profils_folder=${{ env.SHARE_PROFILS_FOLDER }}' ./Packer/Wvd-Image.json

      - name: Build Image Packer
        run: |
          packer build -var 'sp_Id=${{ secrets.SP_ID }}' -var 'sp_Secret=${{ secrets.SP_SECRET }}' -var 'tenant_Id=${{ secrets.TENANT_ID }}' -var 'subscription_Id=${{ secrets.SUBSCRIPTION_ID }}' -var 'image_Rgname=${{ env.IMAGE_RGNAME }}' -var 'image_Name=${{ env.IMAGE_NAME }}' -var 'image_location=${{ env.IMAGE_LOCATION }}' -var 'Os=${{ env.OS }}' -var 'Publisher=${{ env.PUBLISHER}}' -var 'Offer=${{ env.OFFER }}' -var 'Sku=${{ env.SKU }}' -var 'Share_Profils_location=${{ env.SHARE_PROFILS_LOCATION }}' -var 'Share_Profils_folder=${{ env.SHARE_PROFILS_FOLDER }}' ./Packer/Wvd-Image.json
