name: test slack

on:
  push:
    branches:
      - dev    
    paths:
      - "slack/**"

jobs:
  Slack-Test:
    runs-on: ubuntu-latest

    steps:

      - name: Set url
        run: echo '::set-output name=SELECTED_URL::https://github.com/Pierre-Chesne/github-WVD/actions'
        id: url
      - name: Get url
        run: echo "${{ steps.url.outputs.SELECTED_URL }}"

      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Action GitHub "repo github-WVD "
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields":[
                  {
                    "title": "Approuve le déploiement"
                    "vaulue": ${{ secrets.SLACK_WEBHOOK_URL }} 
                  }
                ]
              }
            ] 
      