name: test slack

on:
  push:
    branches:
      - dev    
    paths:
      - "slack/**"

jobs:
  Slack-Test:
    runs-on: ubuntu-latest

    steps:

      - name: Set url
        run: echo '::set-output name=SELECTED_URL::https://github.com/Pierre-Chesne/github-WVD/actions'
        id: url
      - name: Get url
        run: echo "l'url est ${{ steps.url.outputs.SELECTED_URL }}"
      