name: test slack

on:
  push:
    branches:
      - dev    
    paths:
      - "slack/**"

jobs:
  Slack-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Action GitHub 
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields":[
                  {
                    "title": "Approuve le déploiement"
                  }
                ]
              }
            ]  
    


