name: test slack

on:
  push:
    branches:
      - dev    
    paths:
      - "slack/**"

jobs:
  Slack-Test:
    runs-on: ubuntu-latest

    steps:

      - name: Set Message Approuve
        run: |          
          echo "::set-output name=message_url::$(echo "https://github.com/Pierre-Chesne/github-WVD/actions")"
        id: url

      - name: test
        run: |
          echo "The string is: ${{ steps.url.outputs.content.message_url }}"
      