name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    path:
      - "test/**"
    tags:
      - token

    

jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:
      - name: Get Token Expiration
        shell: pwsh
        run: $((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          