name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    paths:
      - "test/**"

env:
  AZURE_RG: "RG-WVD-00" # nom du resource groupe
  AZURE_LOCATION: "eastus2" # region Azure


jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:

      - name: Creation du temp d'expiration du Token (host Pool)
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=content::$($Expiration)"
        id: var_expiration      
      
      - name: Test du temp d'expiration du Token (host Pool)
        run: |
          echo "The string is: ${{ steps.var_expiration.outputs.content }}"

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation du RG
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
            az group create --name ${{ env.AZURE_RG }} --location ${{ env.AZURE_LOCATION }}
            
      - name: Test du Template ARM
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
            az deployment group validate --resource-group RG-WVD-00 --template-file ./ARM/azuredeploy.json  --paramaters 'hostpools_name=Host-Pool-01' 'poolType=pooled' 'lbType=BreadthFirst' 'tokenExpirationTime=${{ steps.var_expiration.outputs.content }}' 'workspaces_name=Workspace-01' 'vmSize=Standard_D2s_v3' 'publisherName=MicrosoftWindowsDesktop' 'offerName=office-365' 'skuName=20h1-evd-o365pp' 'Numbers_of_VM=2' 'host_name_prefix=hostVDI' 'Username=pierrc' 'pwdUser=Password123$' 'domainName=ma-pme.local' 'domainUsername=pierrc@ma-pme.local' 'domainUsernamePassword=Password123$' 'virtualNetworkResourceGroupName=RG-AD-WVD' 'virtualNetworkName=AD-WVD-vnet' 'subnetName=subnet-test'  
