name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    paths:
      - "test/**"

env:
  AZURE_RG: "RG-WVD-00"
  AZURE_LOCATION: "eastus2"


jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:

      - name: Creation du temp d'expiration du Token (host Pool)
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=content::$($Expiration)"
        id: var_expiration      
      
      - name: Test du temp d'expiration du Token (host Pool)
        run: |
          echo "The string is: ${{ steps.var_expiration.outputs.content }}"