name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    paths:
      - "test/**"

env:
  AZURE_RG: "RG-WVD-00" # nom du resource groupe
  AZURE_LOCATION: "eastus2" # region Azure  
  HOSTPOOLS_NAME: "Host-Pool-01" # Nom du Host Pool
  POOLTYPE: "pooled" # Type de Pool "pooled" ou "personal"
  LBTYPE: "BreadthFirst" # Algo "BreathFirst" ou "Deptfirst"
  WORKSPACE_NAME: "Workspace-01" # Nom du Workslace
  VMSIZE: "Standard_D2s_v3" # taille de la 
  NUMBERS_OF_VM: 2 # Nombre de hosts dans le Host Pool
  HOST_NAME_PREFIX: "hostVDI"  
  USERNAME: "pierrc"
  DOMAINNAME: "ma-pme.local"
  VIRTUALNETWORKRESOURCEGROUPNAME: "RG-AD-WVD"
  VIRTUALNETWORKNAME: "AD-WVD-vnet"
  SUBNETNAME: "subnet-test"



jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:

      - name: Creation du temp d'expiration du Token (host Pool)
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=content::$($Expiration)"
        id: var_expiration      
      
      - name: Test du temp d'expiration du Token (host Pool)
        run: |
          echo "The string is: ${{ steps.var_expiration.outputs.content }}"

      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation du RG
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
            az group create --name ${{ env.AZURE_RG }} --location ${{ env.AZURE_LOCATION }}
            
      - name: Test du Template ARM
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
            az deployment group validate --resource-group ${{ env.AZURE_RG }} --template-file ./ARM/azuredeploy.json --parameters 'hostpools_name=${{ env.HOSTPOOLS_NAME }}' 'poolType=${{ env.POOLTYPE }}' 'lbType=${{ env.LBTYPE }}' 'tokenExpirationTime=${{ steps.var_expiration.outputs.content }}' 'workspaces_name=${{ env.WORKSPACE_NAME }}' 'vmSize=${{ env.VMSIZE }}' 'publisherName=MicrosoftWindowsDesktop' 'offerName=office-365' 'skuName=20h1-evd-o365pp' 'Numbers_of_VM=${{ env.NUMBERS_OF_VM }}' 'host_name_prefix=${{ env.HOST_NAME_PREFIX }}' 'Username=${{ env.USERNAME }}' 'pwdUser=${{ secrets.PWD_USER }}' 'domainName=${{ env.DOMAINNAME }}' 'domainUsernamePassword=${{ secrets.DOMAINE_USER_NAME_PASSWORD }}' 'virtualNetworkResourceGroupName=${{ env.VIRTUALNETWORKRESOURCEGROUPNAME }}' 'virtualNetworkName=${{ env.VIRTUALNETWORKNAME }}' 'subnetName=${{ env.SUBNETNAME }}'

      - name: What-If du Template ARM
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
            az deployment group what-if --resource-group ${{ env.AZURE_RG }} --name rollout01 --template-file ./ARM/azuredeploy.json --parameters 'hostpools_name=Host-Pool-01' 'poolType=pooled' 'lbType=BreadthFirst' 'tokenExpirationTime=${{ steps.var_expiration.outputs.content }}' 'workspaces_name=Workspace-01' 'vmSize=Standard_D2s_v3' 'publisherName=MicrosoftWindowsDesktop' 'offerName=office-365' 'skuName=20h1-evd-o365pp' 'Numbers_of_VM=2' 'host_name_prefix=hostVDI' 'Username=pierrc' 'pwdUser=${{ secrets.PWD_USER }}' 'domainName=ma-pme.local' 'domainUsernamePassword=${{ secrets.DOMAINE_USER_NAME_PASSWORD }}' 'virtualNetworkResourceGroupName=RG-AD-WVD' 'virtualNetworkName=AD-WVD-vnet' 'subnetName=subnet-test'
          