name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    paths:
      - "test/**"

env:
  AZURE_RG: "RG-WVD-00"
  AZURE_LOCATION: "eastus2"



jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:
      - name: Get Token Expiration
        shell: pwsh
        run: $((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Creation du RG
        uses: azure/CLI@v1
        with:
          azcliversion: 2.17.1
          inlineScript: |
            az group create --name ${{ env.AZURE_RG }} --location ${{ env.AZURE_LOCATION }}

      
        

    
          