name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    paths:
      - "test/**"

env:
  AZURE_RG: "RG-WVD-00"
  AZURE_LOCATION: "eastus2"



jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:

      - name: Set outputs Expiration
        id: vars
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo '::set-output name=content::$Expiration'

      - name: Display Expiration
        run: |
          echo "${{ steps.vars.outputs.content }}"