name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    paths:
      - "test/**"

env:
  AZURE_RG: "RG-WVD-00"
  AZURE_LOCATION: "eastus2"



jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:

      - name: Set outputs
        id: vars
        shell: pwsh
        run: echo '::set-output name=production::$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))'

      - name: Check outputs
        shell: pwsh
        run: echo "${{ steps.vars.outputs.production }}"


   