name: Test Get Expiratiion Time

on:
  push:
    branches:
      - dev    
    paths:
      - "test/**"

env:
  AZURE_RG: "RG-WVD-00"
  AZURE_LOCATION: "eastus2"



jobs:
  Token-Expiration-Time:
    runs-on: ubuntu-20.04
   
    steps:

      - name: create string
        shell: pwsh
        run: |
          $MY_STRING="hello world"
          echo "::set-output name=content::$$MY_STRING"
        id: my_string
      
      
      - name: display string
        run: |
          echo "The string is: ${{ steps.my_string.outputs.content }}"